# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5274/me
Authorization: Bearer CfDJ8EFQVTA6alBAoMm7smW7iI5B6mbLWUVyiX32UCcPyfu1bC0gSx3t387nwrlFoyTI8x7FOBIyNiEc-2qlP5ePrRQoJZTbzUzzQkdPQnOydaKO336jZjWeWiXQAmJrMZzLeOhDyB3EnAOq_xDEB0mcpA7IfCZSC79GRxN7RIhdrV7ybues1qMaaxgjh1EWKizmT16D4Obuoc3bzNG7ru0toTLwmX7Uqur-HbTVhXU6NisDfS2W_hU4suG65s-QtfCLsB66reHK7zoI3adxdBjAq5fGjxob_jv8JHoqvAia4gb2nR4fP7DqC3BWYSjIMC84phZO9mvH-HeQW3Sj7Wa07XKham8KxUsfkD31XQq4orSOchrYplLy6ClMF-_RZIuiDHwFLSxfI0B24QsI5b8XbYkjwRVHQBF4InQmntTQSnvTGdPk10vaPp_5h-AExcGEHQ8IWZp6DqM31X-dzBwwYU9mHSxAigrsZbWygEre3sqAn8OTRC16h2Z85P0izUkgYEWO5gwbJnd-2ozH1YERRnyumFoB57-MRoDOuJBR941psf6N9_qxYh1iLyOqVXK-yyhjKmbjfraYNJoHUyOQNRQmpSuEopAXHrgAoPvM2sq-7VwhinWar1x0cOdRRplGkeBbdRSGe9E7SPG45q8w4PTUUBsPfz_6Tx8EwdnjEUkE64lV4mw7JG9HHQvGjwC2rg